# Generated by Django 4.2.3 on 2023-12-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='espncrici_player_info',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('player_age', models.CharField(max_length=255)),
                ('player_image', models.CharField(max_length=255)),
                ('player_gender', models.CharField(max_length=10)),
                ('player_playing_role', models.CharField(max_length=255)),
                ('player_country', models.CharField(max_length=255)),
            ],
        ),
    ]
